PACKAGE_NAME="elan-guardian"
PACKAGE_VERSION="0.2.12"
MAKE[0]="env -u KERNELRELEASE make -C rust-shim KDIR=/lib/modules/${kernelver}/build"
CLEAN="env -u KERNELRELEASE make -C rust-shim KDIR=/lib/modules/${kernelver}/build clean"
BUILT_MODULE_NAME[0]="elan_i2c"
BUILT_MODULE_LOCATION[0]="rust-shim"
DEST_MODULE_LOCATION[0]="/kernel/drivers/input/mouse"
AUTOINSTALL="yes"
